// Generated by Wrangler on Tue Aug 27 2024 16:06:48 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DB: D1Database;
}
